server:
  port: 8003

eureka:
  client:
    #register-with-eureka: false  
    #fetch-registry: false
    registerWithEureka: false
    fetchRegistry: false
    service-url: 
      defaultZone: http://root:root@127.0.0.1:${server.port}/eureka/
      
security:
  basic:
    enabled: true
  user:
    name: root
    password: root      
    
logging:
  level:
    root: ERROR    